---
abstract: 'PostgreSQL support for Database::Async'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0.010'
  Test::MockModule: '0'
  Test::More: '0.98'
  Test::Refcount: '0.07'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.020, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Database-Async-Engine-PostgreSQL
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Database::Async::Engine::PostgreSQL:
    file: lib/Database/Async/Engine/PostgreSQL.pm
    version: '0.011'
  Database::Async::Engine::PostgreSQL::DDL:
    file: lib/Database/Async/Engine/PostgreSQL/DDL.pm
    version: '0.011'
requires:
  Config::Tiny: '0'
  Database::Async: '0.014'
  Encode: '0'
  File::HomeDir: '0'
  Future: '0.46'
  Future::AsyncAwait: '0.28'
  Log::Any: '1.050'
  Path::Tiny: '0'
  Protocol::Database::PostgreSQL: '1.005'
  Ryu::Async: '0.017'
  Template: '2.28'
  URI::QueryParam: '0'
  URI::postgres: '0'
  Unicode::UTF8: '0'
  curry: '1.001'
  indirect: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Database-Async-Engine-PostgreSQL/issues
  homepage: https://github.com/team-at-cpan/Database-Async-Engine-PostgreSQL
  repository: https://github.com/team-at-cpan/Database-Async-Engine-PostgreSQL.git
version: '0.011'
x_authority: cpan:TEAM
x_contributors:
  - 'Tom M <tom@audioboundary.com>'
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
